import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import { Roboto_Flex as FontSans } from "next/font/google";
import "@/src/styles/globals.css";
import { cn } from "@/src/lib/utils";
import ThemeProvider from "@/src/components/theme-provider";

const roboto = FontSans({
  weight: ["100", "200", "300", "400", "500"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          "min-h-screen bg-background overflow-hidden font-sans antialiased",
          roboto.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system">
          <SessionProvider>{children}</SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
